baseURL = "gabe.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "Gabe Garcia"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
description = "Data Science & Analytics"

[Menus]
  main = [
      {Name = "GitHub", URL = "https://github.com/gabegarcia15/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gabepgarcia/"},
      {Name = "Twitter", URL = "https://www.twitter.com/gabegarcia15/"}
  ]